//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public string text { get; set; }
        public int userId { get; set; }
        public int replied { get; set; }
        public System.DateTime createDate { get; set; }
        public int songid { get; set; }
    
        public virtual Karbar Karbar { get; set; }
        public virtual Song Song { get; set; }
    }
}
