//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWords
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> songid { get; set; }
        public Nullable<int> singerid { get; set; }
        public Nullable<int> genreid { get; set; }
    }
}
