//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikedSingers
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int SingerId { get; set; }
    
        public virtual Singer Singer { get; set; }
        public virtual User User { get; set; }
    }
}
