//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Comments = new HashSet<Comments>();
            this.LikedSongs = new HashSet<LikedSongs>();
            this.LikedSongText = new HashSet<LikedSongText>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int singerId { get; set; }
        public int languageId { get; set; }
        public int genreId { get; set; }
        public string releaseDate { get; set; }
        public string filelocation { get; set; }
        public int groupId { get; set; }
        public string pic { get; set; }
        public string Note { get; set; }
        public string youtubeAddress { get; set; }
        public string singerName { get; set; }
        public int likes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikedSongs> LikedSongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikedSongText> LikedSongText { get; set; }
        public virtual Singer Singer { get; set; }
        public virtual SongGroup SongGroup { get; set; }
    }
}
